### ISSUE TITLE
Unable to install in Google Cloud AI Platform Notebooks

### ISSUE THREAD

**Issue by gogasca** [jupyterlab/jupyterlab-commenting#32]
```
#sudo jupyter labextension install jupyterlab-commenting --debug
Searching ['/home/gogasca', '/home/gogasca/.jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /usr/etc/jupyter
Looking for jupyter_config in /home/gogasca/.jupyter
Looking for jupyter_config in /home/gogasca
Node v11.15.0

> /usr/bin/npm pack jupyterlab-commenting
npm WARN deprecated jupyterlab-commenting@0.1.0: testing
npm notice 
npm notice 📦  jupyterlab-commenting@0.1.0
npm notice === Tarball Contents === 
npm notice 1.6kB package.json               
npm notice 1.5kB LICENSE                    
npm notice 3.6kB README.md                  
npm notice 181B  style/images/backButton.png
npm notice 2.6kB style/images/chatIcon.png  
npm notice 5.4kB style/index.css            
npm notice === Tarball Details === 
npm notice name:          jupyterlab-commenting                   
npm notice version:       0.1.0                                   
npm notice filename:      jupyterlab-commenting-0.1.0.tgz         
npm notice package size:  7.2 kB                                  
npm notice unpacked size: 14.9 kB                                 
npm notice shasum:        bc21627f3a69794f5749fadc50d49d402750bb16
npm notice integrity:     sha512-+Pq2mMuIrB5aI[...]1eHrdT87q+9qA==
npm notice total files:   6                                       
npm notice 
jupyterlab-commenting-0.1.0.tgz
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/jupyterlab/labextensions.py", line 77, in start
    ans = self.run_task()

  File "/usr/local/lib/python3.5/dist-packages/jupyterlab/labextensions.py", line 106, in run_task
    for arg in self.extra_args

  File "/usr/local/lib/python3.5/dist-packages/jupyterlab/labextensions.py", line 106, in <listcomp>
    for arg in self.extra_args

  File "/usr/local/lib/python3.5/dist-packages/jupyterlab/commands.py", line 219, in install_extension
    return handler.install_extension(extension)

  File "/usr/local/lib/python3.5/dist-packages/jupyterlab/commands.py", line 418, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/usr/local/lib/python3.5/dist-packages/jupyterlab/commands.py", line 1257, in _install_extension
    raise ValueError(msg % (extension, '\n'.join(messages)))

ValueError: "jupyterlab-commenting" is not a valid extension:
Missing extension module "lib/index.js"


Errored, use --debug for full output:
ValueError: "jupyterlab-commenting" is not a valid extension:
Missing extension module "lib/index.js"
```

**Comment by hoo761** [comment]
@gogasca Now that the extension is published to npm, let me know if it installs now. 

Here is the command.
```jupyter labextension install @jupyterlab/commenting-extension```

**Comment by gogasca** [comment]
Installation is successful, will test it, thanks @hoo761

**Comment by gogasca** [comment]
I was able to install it, but unable to run in AI Platform notebooks (Jupyter Lab 1.0.6):
The commenting option is not displayed.

Steps followed:

```
sudo jupyter labextension install @jupyterlab/commenting-extension
```
```
sudo service jupyter restart
```
```
sudo jupyter labextension list
JupyterLab v1.0.6
Known labextensions:
  app dir: /usr/local/share/jupyter/lab
       @jupyterlab/celltags v0.1.5 enabled OK
       @jupyterlab/commenting-extension v0.1.0 enabled OK
       @jupyterlab/git v0.8.1 enabled OK
       nbdime-jupyterlab v1.0.0 enabled OK
```

```
ls -al /usr/local/share/jupyter/lab/extensions/
total 1452
drwxr-sr-x 2 root staff    4096 Aug 27 04:34 .
drwxr-sr-x 8 root staff    4096 Aug 27 04:34 ..
-rw-r--r-- 1 root root    11945 Aug 20 02:03 jupyterlab-celltags-0.1.5.tgz
-rw-r--r-- 1 root root  1394291 Aug 27 04:34 jupyterlab-commenting-extension-0.1.0.tgz
-rw-r--r-- 1 root root    53835 Aug 20 02:02 jupyterlab-git-0.8.1.tgz
-rw-r--r-- 1 root root    11752 Aug 20 02:03 nbdime-jupyterlab-1.0.0.tgz
```
Other extensions work.

Locally using Jupyter Lab 1.0.9 works. (Mac)

Any logs I should be looking at?

Thanks

**Comment by gogasca** [comment]
```
jupyter==1.0.0
jupyter-aihub-deploy-extension==0.1
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.5.0
jupyter-highlight-selected-word==0.2.0
jupyter-http-over-ws==0.0.6
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterlab==1.0.6
jupyterlab-git==0.8.1
jupyterlab-server==1.0.4
```

**Comment by gogasca** [comment]
I did a sudo jupyter lab build
and sudo chown -hR {user} {dir} and worked now.

**Comment by hoo761** [comment]
Awesome. Let me know if you are having any other problems.

**Comment by gogasca** [comment]
@hoo761 thanks for replying, when I tag someone in the comment for example @hoo761 (Your GitHub id) are you supposed to get a notification via GitHub?

**Comment by hoo761** [comment]
@gogasca We are working on a user system to be able to do something similar to that. It is not added as of yet.

Those discussions are here. #22 #23.

**Comment by gogasca** [comment]
Thanks, those will be consider for us like must-have, will track the progress.
